# Generated by Django 4.2.3 on 2023-07-28 16:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("firstapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Posts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.CharField(max_length=255)),
                ("image", models.CharField(max_length=2083)),
                ("link", models.CharField(max_length=2083)),
            ],
        ),
        migrations.DeleteModel(
            name="Offers",
        ),
    ]
