# Generated by Django 4.2.3 on 2023-08-03 19:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("firstapp", "0002_posts_delete_offers"),
    ]

    operations = [
        migrations.AddField(
            model_name="posts",
            name="file",
            field=models.FilePathField(
                default=django.utils.timezone.now,
                path="/Users/ravinderkumar/PycharmProjects/DesignSite/firstapp/word_files",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="posts",
            name="description",
            field=models.CharField(max_length=500),
        ),
    ]
