# Generated by Django 4.2.3 on 2023-08-10 22:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("firstapp", "0003_posts_file_alter_posts_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="posts",
            name="likes",
            field=models.IntegerField(default=0, verbose_name=0),
            preserve_default=False,
        ),
    ]
