# Generated by Django 4.2.3 on 2023-08-11 09:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("firstapp", "0004_posts_likes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="posts",
            name="likes",
        ),
        migrations.AddField(
            model_name="posts",
            name="views",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
