# Generated by Django 4.2.3 on 2023-08-13 12:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("firstapp", "0005_remove_posts_likes_posts_views"),
    ]

    operations = [
        migrations.AddField(
            model_name="posts",
            name="likes",
            field=models.ManyToManyField(
                related_name="blog_post", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
