# Generated by Django 4.2.3 on 2023-08-24 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("firstapp", "0006_posts_likes"),
    ]

    operations = [
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=225)),
                ("comment_text", models.TextField()),
                (
                    "Posts",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Comments",
                        to="firstapp.posts",
                    ),
                ),
            ],
        ),
    ]
